### ISSUE TITLE
CMSMap

### ISSUE THREAD

**Issue by ozeliurs** [WeakSpotter/WeakSpotter#26]
Add CMSMap to Weakspotter.

https://github.com/dionach/CMSmap

**Comment by ozeliurs** [comment]
CMSMap job dies before the end of the analysis:

```
[-] Target: http://ozeliurs.com (38.242.212.45)
Traceback (most recent call last):
  File "/cmsmap/cmsmap.py", line 25, in <module>
    main()
  File "/cmsmap/cmsmap/main.py", line 174, in main
    scanner.RunScanner()
  File "/cmsmap/cmsmap/lib/scanner.py", line 34, in RunScanner
    genericchecker.HTTPSCheck()
  File "/cmsmap/cmsmap/lib/genericchecks.py", line 61, in HTTPSCheck
    requester.noredirect(self.url, data=None)
  File "/cmsmap/cmsmap/lib/requester.py", line 54, in noredirect
    self.response = urllib.request.urlopen(self.req)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 553, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 724, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cmsmap/cmsmap/lib/requester.py", line 90, in redirect_request
    RedirError.status = code
    ^^^^^^^^^^^^^^^^^
AttributeError: property 'status' of 'HTTPError' object has no setter
```

**Comment by ozeliurs** [comment]
Drop tool usage
